Upgrade ‘bdflib’ requirement to 2.0.0
To avoid the error: “cannot import name 'xlfd' from 'bdflib’”.  How was
this even working before?  I must have upgraded by hand and forgotten to
bump the ‘requirements.txt’ file.